certificates:
  - certificate: 
      id: maincaecdsa
      parent: maincaecdsa
      ca: true
      pkix:
        commonname: www.foo.se
        country: SE
        organization: test
        organizationunit: testcaecdsa
      keytype: P224
      hashalg: SHA256
      validto: 2034-01-01
  - certificate:
      id: interca
      parent: maincaecdsa
      ca: true
      pkix:
        commonname: www.bar.se
        country: SE
        organization: test
        organizationunit: testinterca
      keytype: P224
      keylength: 1024
      hashalg: SHA256
  - certificate:
      id: client1sign
      parent: interca
      pkix:
        commonname: www.baz.se
        country: SE
        organization: test
        organizationunit: testweb
      keytype: P224
      keylength: 1024
      hashalg: SHA256
      usage:
        - contentcommitment
  - certificate:
      id: client1encrypt
      parent: interca
      pkix:
        commonname: www.baz.se
        country: SE
        organization: test
        organizationunit: testweb2
      keytype: P224
      keylength: 1024
      hashalg: SHA256
      usage:
        - encipherment

